(function(g){var window=this;var sGa=function(){return{G:"svg",U:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{G:"path",U:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},tGa=function(){return{G:"svg",
U:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{G:"path",U:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},r5=function(a,b){g.OX.call(this,a,{G:"div",
L:"ytp-reminder-menu",U:{role:"menu",tabindex:"-1"},S:[{G:"div",L:"ytp-reminder-menu-contents",S:[{G:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.B=b;this.C=[];this.menuPopupRenderer=void 0;this.items=this.ga("ytp-reminder-menu-items");this.hide()},vGa=function(a){var b=uGa(a),c=0,d={};
for(c=0;c<b.length;d={Qu:d.Qu},c++){var e=a.C[c];e||(e=new g.V({G:"div",L:"ytp-reminder-menu-item",U:{role:"menuitem",tabindex:"0"},S:[{G:"div",L:"ytp-reminder-menu-item-icon",Z:"{{icon}}"},{G:"div",L:"ytp-reminder-menu-item-label",Z:"{{text}}"}]}),d.Qu=c,e.ua("click",function(l){return function(){var m=l.Qu;a.fb();m=uGa(a)[m];a.V("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.fa(a.items),a.C[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=sGa();break;case "NOTIFICATIONS_NONE":h=tGa();break;case "NOTIFICATIONS_ACTIVE":h=g.yN()}f=f.text?g.U(f.text):"";e.update({icon:h,text:f})}for(;c<a.C.length;)a.C.pop().dispose();0===c?a.fb():a.tc(a.B)},uGa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},s5=function(a){g.V.call(this,{G:"div",
S:[{G:"button",ia:["ytp-offline-slate-button","ytp-button"],S:[{G:"div",L:"ytp-offline-slate-button-icon",Z:"{{icon}}"},{G:"div",L:"ytp-offline-slate-button-text",Z:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.u=null;(this.F=this.ga("ytp-offline-slate-button"))&&this.R(this.F,"click",this.I);this.hide()},wGa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);t5(a)},t5=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.U(b.toggledText):"";a.update({text:c,icon:u5(b.toggledIcon)})}else c=b.defaultText?g.U(b.defaultText):"",a.update({text:c,icon:u5(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=xGa(a))?(c=b.text?g.U(b.text):"",a.update({text:c,icon:u5(b.icon)}),a.show()):a.hide():a.hide()},zGa=function(a,b,c){a.D||(a.D=new g.jr(a.J.T().ba));
var d=g.Hp(a.D.Ff||g.Ip());g.rs()&&(d.context.clientScreenNonce=g.rs());d.params=c;g.Kp(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){yGa(a)},
Of:function(){yGa(a)}})},yGa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,t5(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,t5(a))},u5=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return sGa();case "NOTIFICATIONS_NONE":return tGa();case "NOTIFICATIONS_ACTIVE":return g.yN();default:return null}},xGa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.q(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},v5=function(a){g.V.call(this,{G:"div",
L:"ytp-offline-slate",S:[{G:"div",L:"ytp-offline-slate-background"},{G:"div",L:"ytp-offline-slate-bar",S:[{G:"span",L:"ytp-offline-slate-icon",S:[{G:"svg",U:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},S:[{G:"path",U:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",U:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-messages",S:[{G:"div",L:"ytp-offline-slate-main-text",Z:"{{maintext}}"},{G:"div",L:"ytp-offline-slate-subtitle-text",Z:"{{subtitletext}}"}]},{G:"span",L:"ytp-offline-slate-buttons"}]},{G:"button",ia:["ytp-offline-slate-close-button","ytp-button"],S:[g.lN()]},{G:"button",ia:["ytp-offline-slate-open-button","ytp-button"],S:[g.kN()]},{G:"div",L:"ytp-offline-slate-trailer-chip",Z:"Trailer"}]});var b=this;this.api=a;this.B=this.u=
null;this.background=this.ga("ytp-offline-slate-background");this.D=this.ga("ytp-offline-slate-bar");this.F=new g.H(function(){g.I(b.D,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.H(function(){g.I(b.element,"ytp-offline-slate-collapsed")},15E3);
g.C(this,this.C);g.C(this,this.F);this.countdownTimer=new g.H(this.uG,1E3,this);this.R(a,"presentingplayerstatechange",this.xG);this.R(a,"livestatedata",this.na);a=this.ga("ytp-offline-slate-close-button");this.R(a,"click",function(){g.I(b.element,"ytp-offline-slate-collapsed")});
a=this.ga("ytp-offline-slate-open-button");this.R(a,"click",function(){g.Bn(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.na(a)},w5=function(a,b,c){if(b){var d=null!=b.subtitleText?g.U(b.subtitleText):"";
b=c?c:null!=b.mainText?g.U(b.mainText):"";a.getVideoData();a.update({maintext:b,subtitletext:d});g.J(a.element,"ytp-offline-slate-single-text-line",!d)}},x5=function(a,b){var c=(0,g.N)();
this.trigger=a;this.u=b;this.C=c},z5=function(a){g.pS.call(this,a);
var b=this;this.K=!1;this.N=0;this.F=!1;this.B=new g.H(function(){var e=b.player.T(),f=b.getVideoData();if(y5(b))if(AGa(b)){var h;null!==(h=b.heartbeatParams)&&void 0!==h&&h.url&&(e=g.Ld(b.heartbeatParams.url,{request_id:g.js()}),f.Vf&&(e=g.Ld(e,{vvt:f.Vf}),f.mdxEnvironment&&(e=g.Ld(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.Ld(e,{access_token:f.oauthToken})),BGa(b,f,e))}else CGa(b,e,f)},0);
this.u=this.heartbeatParams=null;this.C=!1;this.I=new g.Mn(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.W=new g.jr(void 0);this.utcOffsetMinutes=-(new g.Yf).getTimezoneOffset();this.D=new g.Wr(this);this.P=void 0;g.C(this,this.B);g.C(this,this.D);DGa(this);this.D.R(a,"heartbeatparams",this.OK);this.D.R(a,"presentingplayerstatechange",this.PK);this.D.R(a,"videoplayerreset",this.QK);this.D.R(a,g.wD("heartbeat"),this.NK);this.C&&this.u&&EGa(this,this.u);var c=new g.tD(1E3,0x7ffffffffffff,
{priority:0,namespace:"heartbeat"}),d=new g.tD(0x8000000000000,0x8000000000000,{id:"stream_end",priority:0,namespace:"heartbeat"});g.GM(a,[c,d])},AGa=function(a){var b=a.getVideoData();
return!g.xF(a.getVideoData())||b.gC?!1:g.R(a.player.T().experiments,"use_innertube_hearbeats_for_playready")?!!b.Wc&&"widevine"===b.Wc.flavor:!0},A5=function(a){return AGa(a)?!!a.heartbeatParams:!!a.getVideoData().heartbeatToken},B5=function(a,b){if(!a.B.isActive()&&a.K){var c=a.getVideoData();
if(A5(a)||c.isLivePlayback){if(void 0===b){if(a.F){var d;c=a.C?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().WB||6E4}else c=1E3;b=c}a.B.start(b)}}},BGa=function(a,b,c){b.hp&&(c=g.Ld(c,{internalipoverride:b.hp}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.lh&&(d.kpt=b.lh);c=g.Ld(c,d);g.oq(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&y5(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=FGa(e);if(f){a.player.va("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(GGa))?"0"===h[1]?0:1:-1;HGa(a,f,e,h)}},
onError:function(e){y5(a)&&C5(a,!0,"net-"+e.status)},
Of:function(){y5(a)&&C5(a,!0,"timeout")},
withCredentials:!0})},y5=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.T(g.lI(a.player,a.getPlayerType()),4)?!1:A5(a)||b.isLivePlayback?!0:(D5(a),!1)},CGa=function(a,b,c){var d={videoId:c.videoId,
sequenceNumber:a.sequenceNumber},e=g.kG();null==e.user&&(e.user={});null==e.request&&(e.request={});c.mdxEnvironment&&(e.request.mdxEnvironment=c.mdxEnvironment);c.lh&&(e.user.kidsParent={oauthToken:c.lh});c.Vf&&(e.user.credentialTransferTokens=[{token:c.Vf,scope:"VIDEO"}]);var f=b.deviceParams,h=b.ba,l={utcOffsetMinutes:a.utcOffsetMinutes};b.experiments.experimentIds&&(l.experimentIds=b.experiments.experimentIds.map(Number));f&&(l.deviceMake=f.cbrand||"www",l.deviceModel=f.cmodel||"www",l.browserName=
f.cbr,l.browserVersion=f.cbrver,l.osName=f.cos,l.osVersion=f.cosver);h&&(l.clientName=h.fp,l.clientVersion=h.innertubeContextClientVersion,l.hl=h.As,l.gl=h.zs);f=a.player.T();f.homeGroupInfo&&(l.homeGroupInfo=JSON.parse(f.homeGroupInfo));if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)l.timeZone=h;f.livingRoomAppMode&&(l.tvAppInfo={livingRoomAppMode:f.livingRoomAppMode});e.client=l;c.contextParams&&(l=c.contextParams)&&(e.activePlayers=[],e.activePlayers.push({playerContextParams:l}));
d.context=e;d.cpn=c.clientPlaybackNonce;e={heartbeatChecks:[]};if(l=c.getPlayerResponse())d.heartbeatToken=c.heartbeatToken,(l=l.playabilityStatus)&&(l=l.liveStreamability)&&l.liveStreamabilityRenderer&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.mC(b)&&(e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),c.Zd&&(d.context.client.unpluggedLocationInfo=c.Zd),d.context.client.unpluggedAppInfo={enableFilterMode:c.Dq},
(b=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(b)&&(l={},l.clientPlayerPositionUtcMillis=""+Math.floor(1E3*b),e.unpluggedParams=l));d.heartbeatRequestParams=e;b={timeout:3E4,onSuccess:function(m){if(!a.B.isActive()&&y5(a)){var n=m.playabilityStatus,p=JSON.stringify(n)||"{}",r=-1,t=m.playabilityStatus;t&&(a.player.va("onHeartbeat",t),"OK"===t.status?r=m.stopHeartbeat?2:0:"UNPLAYABLE"===t.status?r=1:"LIVE_STREAM_OFFLINE"===t.status&&(r=0));m=r;a.sequenceNumber&&-1===m||a.I.reset();
a.sequenceNumber++;HGa(a,n,p,m)}},
onError:function(m){y5(a)&&C5(a,!0,"net-"+m.status)},
Of:function(){y5(a)&&C5(a,!0,"timeout")}};
c.kf()&&(b.oA="Bearer "+c.kf());g.Kp(a.W,"player/heartbeat",d,b)},HGa=function(a,b,c,d){if(-1===d)b="decode "+g.rf(c),C5(a,!1,b);
else if(2===d)D5(a),a.F=!0;else if(a.N=0,a.B.stop(),1===d){a.F=!1;a=a.player;d="LICENSE";var e=FGa(c);e?c=e.reason||g.HX[d]||"":((c=c.match(GGa))&&(c=Number(c[1]))&&(d=g.aL(c)),c=g.HX[d]||"");a.app.C.Td("heartbeat.stop",c,void 0,void 0);g.Lq("heartbeatActionPlayerHalted",IGa(b))}else a.F=!0,c=0,a.C&&b&&(c=EGa(a,b),a.player.V("livestatedata",b)),c?B5(a,c):B5(a)},EGa=function(a,b){var c,d=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,e=!(!d||!d.switchStreamsImmediately),f=JGa(d),
h=a.getVideoData(),l=g.lI(a.player,a.getPlayerType());
if(l.Gb()&&!g.GF(h)&&!a.player.isAtLiveHead(a.getPlayerType())&&!e)return f;e=d&&d.streamTransitionEndpoint&&d.streamTransitionEndpoint.watchEndpoint;var m=d&&d.transitionTiming;if(e)if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===m)a.P=e;else if(KGa(a,e))return f;if("OK"===b.status.toUpperCase()){e=d&&d.broadcastId;m=a.u&&a.u.liveStreamability&&a.u.liveStreamability.liveStreamabilityRenderer&&a.u.liveStreamability.liveStreamabilityRenderer.broadcastId;var n=e!==m&&(null!=e||a.player.ca("web_player_heartbeat_undefined_killswitch"));
if(!h.hlsvp&&!h.Hf||n){var p={video_id:h.videoId};h.Fs&&(p.is_live_destination="1");a.player.ca("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=h.watchNextResponse);p.autonav_state=h.autonavState;p.loadContexts=h.rj;a.ie()&&g.FM(a.player,8);l=void 0;h.hlsvp||h.Hf?n&&(l=new x5("broadcastIdChanged",m+","+e),E5("HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED")):(l=new x5("formatsReceived",""+e),E5("HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE"));
a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,l);return f}g.dX(a.player,"heartbeat",a.getPlayerType())}d&&d.displayEndscreen&&(h=a.player.T(),a.offlineSlate?(p=a.offlineSlate,p.I=!0,p.Wa&&g.t0(p.api.app,void 0)):g.R(h.experiments,"html5_heartbeat_set_ended")&&g.iL(l)&&(h=(null===(c=a.player.app.F)||void 0===c?void 0:c.jb())||{},h=g.UA(h),l=!0,l=void 0===l?!1:l,null===(p=g.Z(a.player.app,void 0))||void 0===p?void 0:p.qb("hbse",h,l),g.t0(a.player.app,void 0)));return f},JGa=function(a){var b=
0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},C5=function(a,b,c){if(!a.B.isActive()){a.B.stop();
a.N++;var d=a.getVideoData();if(d.YB||b&&!g.xF(a.getVideoData())&&!A5(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.eq)?f=a.heartbeatParams.eq:f=d.XB||5;e=a.N>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=IGa()),g.Lq("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.app.C.Td(b,"Video playback interrupted. Please try again.",c,void 0):a.player.app.C.Td(b,"Sorry, there was an error licensing this video.",
c,void 0)):(B5(a,a.I.getValue()),g.Nn(a.I))}},IGa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},E5=function(a){g.Lq("heartbeatActionPlayerTransitioned",{trigger:"HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
reason:a})},D5=function(a){a.N=0;
a.B.stop();a.F=!1;a.sequenceNumber=0},DGa=function(a){var b=a.getVideoData(),c=a.player.T();
if(b.isLivePlayback)if(g.yB(c.D)){a.C=!0;a.K=!0;if(!g.$B(c)||g.mC(c))a.offlineSlate=new v5(a.player),g.C(a,a.offlineSlate),g.oP(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.u=b.playabilityStatus);a.u?(b=JGa(a.u.liveStreamability&&a.u.liveStreamability.liveStreamabilityRenderer))?B5(a,b):B5(a,7500):B5(a,1E3)}else a.player.app.C.Td("html5.unsupportedlive","HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1",void 0);else!g.R(c.experiments,"html5_release_post_live_heartbeat_killswitch")&&
g.nb(b.Ie,"heartbeat")&&g.dX(a.player,"heartbeat",a.getPlayerType())},KGa=function(a,b){var c=b&&b.videoId;
return c?(g.M0(a.player.app,c,void 0,void 0,!0,b),E5("HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),!0):!1},FGa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}};
g.u(r5,g.OX);r5.prototype.hide=function(){this.B&&this.B.removeAttribute("aria-haspopup");g.OX.prototype.hide.call(this)};
r5.prototype.show=function(){this.B&&this.B.setAttribute("aria-haspopup","true");g.OX.prototype.show.call(this)};
r5.prototype.aa=function(){g.fg(this.C);g.OX.prototype.aa.call(this)};g.u(s5,g.V);
s5.prototype.I=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;t5(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.u&&this.u.Wa)this.u.fb();else{var b=xGa(this);b&&this.C(b.serviceEndpoint||b.command);b=g.q(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.u||(this.u=new r5(this.J,this.F),this.u.fa(this.element),g.C(this,this.u),this.u.subscribe("reminderMenuItemClicked",this.C,this));b=this.u;b.menuPopupRenderer=a;vGa(b)}};
s5.prototype.C=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(zGa(this,c,b.params),a=g.q(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.B=
b.updateUpcomingEventReminderButtonStateCommand.state;t5(this);break}}};g.u(v5,g.V);g.k=v5.prototype;g.k.getPlayerType=function(){if(this.ie())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.ie=function(){return 8===this.api.getPresentingPlayerType()};
g.k.na=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.u=a;b=b.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.uG():w5(this,b);var c=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail;
if(c){var d=0,e=null;c=c.thumbnails;for(var f=0;f<c.length;f++)c[f].width>d&&(d=c[f].width||0,e=c[f].url);e&&(this.background.style.backgroundImage="url("+e+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.B||(this.B=new s5(this.api),this.B.fa(this.ga("ytp-offline-slate-buttons")),g.C(this,this.B)),wGa(this.B,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.B&&wGa(this.B,null,null);this.u=a}else this.u=null;this.xG()};
g.k.xG=function(a){if(this.ie())var b=!0;else{var c=g.lI(this.api),d=this.getVideoData();b=d.isLivePlayback&&(g.iL(c)||g.T(c,2)||g.T(c,64));var e=2===d.autonavState&&g.T(c,2);c=c.Gb()&&!g.GF(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u&&"LIVE_STREAM_OFFLINE"===this.u.status.toUpperCase()?this.Wa?a&&g.xI(a,2)&&(g.Bn(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.Bn(this.D,"ytp-offline-slate-bar-fade"),this.F.start()):(a=this.ie(),g.J(this.element,"ytp-offline-slate-premiere-trailer",
a),this.show(),this.C.start(),this.api.V("offlineslatestatechange"),this.I&&g.t0(this.api.app,void 0)):this.Wa&&(this.hide(),this.api.V("offlineslatestatechange"))};
g.k.uG=function(){var a=this.u&&this.u.liveStreamability&&this.u.liveStreamability.liveStreamabilityRenderer&&this.u.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.u.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor(g.A()/1E3),c=a.canShowCountdown&&Number(a.scheduledStartTime);!c||c<=b?(w5(this,a),this.countdownTimer.stop()):(b=g.PO(c-b),w5(this,a,b),this.countdownTimer.xb())}};
g.k.aa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.aa.call(this)};x5.prototype.B=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.u===a.u:!1};
x5.prototype.isExpired=function(){return 3E4<(0,g.N)()-this.C};
x5.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.u};g.u(z5,g.pS);g.k=z5.prototype;g.k.aa=function(){D5(this);g.cX(this.player,"heartbeat");g.pS.prototype.aa.call(this)};
g.k.NK=function(a){this.K=!0;B5(this,2E3);var b=this.getVideoData();a&&"stream_end"===a.getId()&&b.aF&&KGa(this,this.P)};
g.k.OK=function(a){this.heartbeatParams=a;B5(this,2E3)};
g.k.PK=function(a){this.ie()||(g.T(a.state,2)||g.T(a.state,64)?(D5(this),this.C&&(this.K=!0,B5(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&B5(this,2E3))};
g.k.QK=function(){3!==this.player.getPresentingPlayerType()&&B5(this,2E3)};
g.k.getPlayerType=function(){if(this.ie())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.ie=function(){return 8===this.player.getPresentingPlayerType()};
g.k.Dh=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.YJ=function(){return!!this.offlineSlate&&this.offlineSlate.Wa};
var GGa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.qX.heartbeat=z5;})(_yt_player);
